apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: zabbix
  labels:
    app: zabbix-server
spec:
  selector:
    app: zabbix-server
  ports:
  - name: zabbix-server
    port: 10051
    nodePort: 30051
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-mysql-configmap
  namespace: zabbix
  labels:
    app: zabbix-server
data:
  mysql.service.name: "zabbix-mysql"
  mysql.db.name: "zabbix"
  mysql.port: "3306"
  mysql.user: "zabbix"
  mysql.password: "zabbix"
