apiVersion: v1
kind: Pod  
metadata:
  name: emptydir-volume-template        # 定义名称
  namespace: default
spec:   # 必选，Pod中容器的详细定义
  containers:   # 必选，Pod中容器列表
  - name: nginx
    image: nginx:1.17.1
    imagePullPolicy: IfNotPresent
    command: ["bash","-c","for i in {1..100};do echo $i >>/tmp/hello.txt;sleep 1;done"]
    ports:
    - containerPort: 80
    volumeMounts:       # 将logs-volume挂载到nginx容器中的目录路径
    - name: logs-volume
      mountPath: /tmp
      readOnly: false   # 是否只读，默认false
  - name: busybox
    image: busybox:1.30
    imagePullPolicy: IfNotPresent
    command: ["bash","-c","tail -f /tmp/hello.txt"]     # 初始命令，动态读取指定文件
    volumeMounts:       # 将logs-volume挂载到busybox容器中的目录路径
    - name: logs-volume
      mountPath: /tmp
  volumes:      # 声明volume，name为logs-volume，类型为emptyDir
  - name: logs-volume   # 共享存储卷名称 （volumes类型有很多种）
    emptyDir: {}        # 类型为emtyDir的存储卷，与Pod同生命周期的一个临时目录。为空值，使用 emptyDir: {} 表使用默认值
     # medium: string   # 存储介质，支持Memory和空字符串(默认)
     # sizeLimit: string        # 大小限制，默认不限制。一般在使用Memory时会限制