apiVersion: v1
kind: Pod
metadata:
  name: nfs-volume-template
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.17.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:  	# 将logs-volume挂载到nginx容器中的目录路径
    - name: logs-volume
      mountPath: /var/log/nginx
  - name: busybox
    image: busybox:1.30
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c","tail -f /logs/access.log"]  	# 初始命令，动态读取指定文件
    volumeMounts:  	# 将logs-volume挂载到busybox容器中的目录路径
    - name: logs-volume
      mountPath: /logs
  volumes:  	# 声明volume
  - name: logs-volume
    nfs:  	# 存储类型，和底层正则的存储对应
      server: 192.168.18.100  	# NFS服务器地址
      path: /root/data/nfs  	# 共享文件路径
      readOnly: false  	# 是否只读，默认false
