##########   定义Redis的静态 PV持久卷   ##########
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-template
  namespace: default
  labels:
    name: redis-pv-template
spec:
  capacity:  	# 存储能力，目前只支持存储空间的设置
    storage: 10Gi  	# 限制容量为 10G
  volumeMode: Filesystem    # 存储类型为文件系统
  accessModes:  	# 访问模式
  - ReadWriteMany  	# Read：读、Write：写、Once：单节点、Many：代表多节点，Only：只读只写
  persistentVolumeReclaimPolicy: Retain   # 回收策略：Retain：保留、Recycle：回收、Delete：删除
  storageClassName: nfs  	# 创建 PV 的存储类的自定义名字，PVC需要于此相同，存储类型，分别为： NFS、CephFS、iSCSI
  mountOptions:  	# 加载配置
  - hard
  - nfsvers=4.1  	# NFS 版本
  nfs:  	# 存储类型，和storageClassName的存储类别对应
    path: /opt/data/redis  	# nfs 授权目录
    server: 192.168.186.110  	# nfs 所在服务器PV持久卷

--- # 分隔符可以定义多个
##########   定义Nginx的静态 PV持久卷   ##########
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-template
  namespace: default
  labels:
    name: nginx-pv-template
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:  	# 加载配置
  - hard
  - nfsvers=4.1  	# NFS 版本
  nfs:
    path: /opt/data/nginx
    server: 192.168.186.110
