apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume-template
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.17.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:  	# 将logs-volume挂载到nginx容器中的目录路径
    - name: logs-volume
      mountPath: /var/log/nginx
  - name: busybox
    image: busybox:1.30
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c","tail -f /logs/access.log"]  	# 初始命令，动态读取指定文件
    volumeMounts:  	# 将logs-volume挂载到busybox容器中的目录路径
    - name: logs-volume
      mountPath: /logs
  volumes:  	# 声明volume，name为logs-volume，类型为hostPath
  - name: logs-volume
    hostPath:  	# 类型为hostPath的存储卷，表示挂载Pod所在宿主机的目录
      path: /opt/logs  	# Pod所在宿主机的目录，将被用于同期中mount的目录
      type: DirectoryOrCreate  	# 目录存在就使用，不存在就先创建再使用 
