##########   定义Redis的静态 PV持久卷   ##########
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-template
  namespace: default
  labels:
    name: redis-pv-template
spec:
  capacity:  	# 存储能力，目前只支持存储空间的设置
    storage: 10Gi  	# 限制容量为 10G
  accessModes:  	# 访问模式
  - ReadWriteMany  	# Read:代表可读、Write:代表写、Many:代表多节点
  storageClassName: nfs  	# 存储类别
  persistentVolumeReclaimPolicy: Retain  	# 回收策略，Retain:保留、Delete:删除
  nfs:  	# 存储类型，和storageClassName的存储类别对应
    path: /opt/data/redis  	# nfs 授权目录
    server: 192.168.94.110  	# nfs 所在服务器PV持久卷

--- # 分隔符可以定义多个
##########   定义Nginx的静态 PV持久卷   ##########
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx
  namespace: default
  labels:
    name: nginx
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /opt/data/nginx
    server: 192.168.94.110