##########   定义Redis的PVC申请书，用于申请 Redis的PV   ##########
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-template
  namespace: default
  labels:
    name: redis-pvc-template
spec:
  accessModes:  	# 访问模式
  - ReadWriteMany  	# Read:代表可读、Write:代表写、Many:代表多节点
  selector:  	# 采用标签对PV选择
    matchLabels:    # 按照Labels标签匹配副本
    - name: redis-pvc-template
  storageClassName: nfs  	# 存储类型 ，Block:代表块存储、Filesystem:代表文件系统、nfs
  resources:  	# 请求空间
    requests:
      storage: 5Gi  	# 对PV申请 5G 的存储空间

---
##########  	创建 Pod 访问 PVC 类型存储   ##########
apiVersion: v1
kind: Deployment
metadata:
  name: redis
  namespace: default
  labels:
    name: redis
spec:
  nodeSelector:
    kubernetes.io/hostname: kube-01  	# 指定节点
  containers:
  - name: reids
    image: redis:6.2.7
    command: ["/bin/sh","-c","while true;do echo pod1 >> /root/out.txt; sleep 10; done;"]
    volumeMounts:
    - name: redis-data
      mountPath: /opt/redis/conf  	# 容器内路径
    - name: redis-config
      mountPath: /opt/redis/logs
  volumes:
  - name: redis-data
    persistentVolumeClaim:  	# 指定PVC
      claimName: redis-pvc-template  	# PVC对象名称，必须要和当前pod在同一个名称空间
      readOnly: false  	# 是否只读，默认false
